elecCalc/urls.py
from django.urls import path

from elecCalc.views import DisplayCableView, DisplayDevicesView, \
    EditCableView, EditDeviceView, DeleteCableView, \
    DeleteDeviceView, AddCableView, AddDeviceView, \
    MainPage, CableListView, CableIddView, export_to_csv, DeleteResultView, PositionChange, LoginView, LogoutView, \
    RegisterView

app_name = 'elecCalc'

urlpatterns = [
    path('', MainPage.as_view(), name='main_page'),
    path('display-cable/', DisplayCableView.as_view(), name='display-cable'),
    path('display-device/', DisplayDevicesView.as_view(), name='display-device'),
    path('edit-cable/<int:cable_id>/', EditCableView.as_view(), name='edit-cable'),
    path('edit-device/<int:device_id>/', EditDeviceView.as_view(), name='edit-device'),
    path('delete-cable/<int:cable_id>/', DeleteCableView.as_view(), name='delete-cable'),
    path('delete-device/<int:device_id>/', DeleteDeviceView.as_view(), name='delete-device'),
    path('delete-cable-list/<int:result_id>/', DeleteResultView.as_view(), name='delete-result'),
    path('add-cable/', AddCableView.as_view(), name='add-cable'),
    path('add-device/', AddDeviceView.as_view(), name='add-device'),
    path('cable-list/', CableListView.as_view(), name='cable-list'),
    path('display-idd/', CableIddView.as_view(), name='display-idd'),
    path('position/', PositionChange.as_view(), name='position'),
    path('export-to-csv/', export_to_csv, name='csv'),
    path('account/register/', RegisterView.as_view(), name='register'),
    path('account/login/', LoginView.as_view(), name='login'),
    path('account/logout/', LogoutView.as_view(), name='logout'),
]

eselprojekt_calc/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('elecCalc.urls')),
]

elecCalc/models.py
from django.db import models

# Create your models here.

OVERLOAD_FACTOR_CHOICES = (
    ('1.2', '1.2'),
    ('1.45', '1.45'),
    ('1.6', '1.6'),
    ('1.9', '1.9'),
)

CABLE_CROSS_SECTION_CHOICES = (
    ('1.5', '1.5'),
    ('2.5', '2.5'),
    ('4', '4'),
    ('6', '6'),
    ('10', '10'),
    ('16', '16'),
    ('25', '25'),
    ('35', '35'),
    ('50', '50'),
    ('70', '70'),
    ('95', '95'),
    ('125', '125'),
    ('150', '150'),
    ('185', '185'),
    ('240', '240'),
)

CABLE_INSULATION_CHOICES = (
    ('PVC', 'PVC'),
    ('XLPE', 'XLPE'),
)

CABLE_TYPE_CHOICES = (
    ('Al', 'Al'),
    ('Cu', 'Cu'),
)

ROUTING_CHOICES = (
    ('A1', 'A1'),
    ('A2', 'A2'),
    ('B1', 'B1'),
    ('B2', 'B2'),
    ('C', 'C'),
    ('D', 'D'),
    ('E', 'E'),
    ('F1', 'F1'),
    ('F2', 'F2'),
    ('F3', 'F3'),
    ('G', 'G'),
)

OVERCURRENT_TYPE_CHOICES = (
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D'),
    ('gG', 'gG'),
    ('Compact', 'Compact'),
)

CURRENT_CHOICES = (
    ('10', '10'),
    ('16', '16'),
    ('25', '25'),
    ('40', '40'),
    ('50', '50'),
    ('80', '80'),
    ('100', '100'),
    ('125', '125'),
    ('160', '160'),
    ('200', '200'),
    ('250', '250'),
    ('315', '315'),
    ('400', '400'),
    ('630', '630'),
    ('800', '800'),
    ('1000', '1000'),
    ('1250', '1250'),
    ('1600', '1600'),
    ('2500', '2500'),
    ('4000', '4000'),
)

DEVICE_NAME_CHOICES = (
    ('WN', 'wyłącznik nadprądowy'),
    ('WS', 'wyłącznik selektywny'),
    ('WK', 'wyłącznik kompaktowy'),
    ('WP', 'wyłącznik powietrzny'),
    ('B', 'wkładka bezpiecznikowa'),
)

POWER_TRAFO_CHOICES = (
    ('100', '100'),
    ('160', '160'),
    ('200', '200'),
    ('250', '250'),
    ('315', '315'),
    ('400', '400'),
    ('500', '500'),
    ('630', '630'),
    ('800', '800'),
    ('1000', '1000'),
    ('1250', '1250'),
    ('1600', '1600'),
    ('2000', '2000'),
    ('2500', '2500'),
    ('3150', '3150'),
)

class Cable(models.Model):
    material = models.CharField(max_length=6, choices=CABLE_TYPE_CHOICES, default='Cu')  # materiał Cu Al
    insulation = models.CharField(max_length=6, choices=CABLE_INSULATION_CHOICES, default='PVC')  # izolacja
    cable_cross_section = models.CharField(max_length=6, choices=CABLE_CROSS_SECTION_CHOICES, default='2.5')  # przekrój
    capacity = models.DecimalField(max_digits=4, decimal_places=1)  # obciążalnosc długotrwała
    cable_routing = models.CharField(max_length=2, choices=ROUTING_CHOICES, default='E')  # sposób ułożenia

    def __str__(self):
        return f'{self.get_material_display()}/{self.get_insulation_display()}/{self.get_cable_cross_section_display()}/' \
               f'{self.get_cable_routing_display()}'


class ProtectionDevices(models.Model):
    name = models.CharField(max_length=2, choices=DEVICE_NAME_CHOICES, default='WN')
    type = models.CharField(max_length=12, choices=OVERCURRENT_TYPE_CHOICES, default='B')  # typ zabezpieczenia
    current = models.CharField(max_length=6, choices=CURRENT_CHOICES, default='16')  # amperaż zabezpieczenia
    cable = models.ForeignKey(Cable, on_delete=models.SET_NULL, null=True, blank=True, related_name="devices")

    def __str__(self):
        return f"{self.get_type_display()}/{self.get_current_display()}A"

class Transformer(models.Model):
    power = models.IntegerField(choices=POWER_TRAFO_CHOICES, default=630)
    load_loss = models.DecimalField(max_digits=5, decimal_places=4, null=True, blank=True) #straty ociążeniowe
    no_load_loss = models.DecimalField(max_digits=5, decimal_places=4, null=True, blank=True) #straty jałowe
    reactance = models.DecimalField(max_digits=5, decimal_places=4, null=True, blank=True)
    resistance = models.DecimalField(max_digits=5, decimal_places=4, null=True, blank=True)
    device = models.ForeignKey(ProtectionDevices, on_delete=models.SET_NULL, null=True, blank=True, related_name="transformers")

    def __str__(self):
        return f"Trafo:{self.power}A"

class CalculationResult(models.Model):
    position = models.IntegerField()
    cir_number = models.CharField(max_length=12)
    cir_name = models.CharField(max_length=64)
    cir_voltage = models.DecimalField(max_digits=4, decimal_places=2)
    cir_power = models.DecimalField(max_digits=6, decimal_places=2)
    cir_cos_fi = models.DecimalField(max_digits=3, decimal_places=2)
    cir_current = models.DecimalField(max_digits=6, decimal_places=2)
    cab_amount = models.IntegerField()
    core_amount = models.IntegerField()
    cab_routing = models.CharField(max_length=2)
    cab_insulation = models.CharField(max_length=4)
    cab_material = models.CharField(max_length=2)
    cab_cable_cross_section = models.DecimalField(max_digits=4, decimal_places=1)
    cab_length = models.IntegerField()
    cab_i_dd = models.DecimalField(max_digits=4, decimal_places=1)
    cab_kc_factor = models.DecimalField(max_digits=3, decimal_places=2)
    cab_i_z = models.DecimalField(max_digits=4, decimal_places=1)
    dev_type = models.CharField(max_length=12)
    dev_current = models.IntegerField(default=2)
    dev_kr_factor = models.DecimalField(max_digits=3, decimal_places=2)
    dev_i_r = models.DecimalField(max_digits=6, decimal_places=2)
    dev_k2_factor = models.DecimalField(max_digits=5, decimal_places=2)
    dev_i_2 = models.DecimalField(max_digits=6, decimal_places=2)
    conditions = models.CharField(max_length=6)
    cab_vol_drop = models.DecimalField(max_digits=4, decimal_places=2)

elecCalc/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import math, csv

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, JsonResponse
from django.views import View
from django.shortcuts import render, redirect
from django import forms
from django.http import HttpRequest

# Create your views here.
from elecCalc.forms import CableForm, ProtectionDevicesForm, CableSelectForm, LoginForm, RegisterForm
from elecCalc.models import Cable, ProtectionDevices, CalculationResult


class Choices:

    voltage_choices = (
        (0, 0.23),
        (1, 0.4),
        (2, 15),
    )

    time_off = (
        (0, 0.2),
        (1, 0.4),
        (2, 5),
    )

    k2_factor = (
        (0, 1.2),
        (1, 1.45),
        (2, 1.6),
        (3, 1.9),
    )

class MainPage(View):

    def get(self, request):

        voltages = [voltage[1] for voltage in Choices.voltage_choices]
        materials = [cable for cable in Cable.objects.all().distinct('material')]
        insulations = [cable for cable in Cable.objects.all().distinct('insulation')]
        cable_cross_sections = [cable for cable in Cable.objects.all().distinct('cable_cross_section')]
        cables_routing = [cable for cable in Cable.objects.all().distinct('cable_routing')]
        names = [devices for devices in ProtectionDevices.objects.all().distinct('name')]
        currents = [devices for devices in ProtectionDevices.objects.all().distinct('current')]
        times_off = [time_off[1] for time_off in Choices.time_off]
        k2_factors = [k2_factor[1] for k2_factor in Choices.k2_factor]
        return render(request, 'main_page.html', context={'voltages': voltages, 'materials': materials,
                                                          'insulations': insulations, 'cable_cross_sections': cable_cross_sections,
                                                          'cables_routing': cables_routing, 'names': names, 'currents': currents,
                                                          'times_off': times_off, 'k2_factors': k2_factors})

    def post(self, request):
        position = int(CalculationResult.objects.all().count()) + 1
        voltages = [voltage[1] for voltage in Choices.voltage_choices]
        materials = [cable for cable in Cable.objects.all().distinct('material')]
        insulations = [cable for cable in Cable.objects.all().distinct('insulation')]
        cable_cross_sections = [cable for cable in Cable.objects.all().distinct('cable_cross_section')]
        cables_routing = [cable for cable in Cable.objects.all().distinct('cable_routing')]
        names = [devices for devices in ProtectionDevices.objects.all().distinct('name')]
        currents = [devices for devices in ProtectionDevices.objects.all().distinct('current')]
        times_off = [time_off[1] for time_off in Choices.time_off]
        k2_factors = [k2_factor[1] for k2_factor in Choices.k2_factor]

        circuit_number = request.POST.get('circuit_number')
        receiver_name = request.POST.get('receiver_name')
        voltage = float(request.POST.get('voltage'))
        power = int(request.POST.get('power'))
        power_factor = float(request.POST.get('power_factor'))
        material = request.POST.get('material')
        insulation = request.POST.get('insulation')
        cable_cross_section = request.POST.get('cable_cross_section')
        cable_routing = request.POST.get('cable_routing')
        amount = int(request.POST.get('amount'))
        core = int(request.POST.get('core'))
        layer_factor = float(request.POST.get('layer_factor'))
        length = int(request.POST.get('length'))
        device_type = request.POST.get('device_type')
        current = int(request.POST.get('current'))
        kr_factor = float(request.POST.get('kr_factor'))
        off_time = float(request.POST.get('off_time'))
        k2_factor = float(request.POST.get('k2_factor'))
        i_dd = float(Cable.objects.filter(material=material, insulation=insulation,
                                      cable_cross_section=cable_cross_section,
                                      cable_routing=cable_routing).first().capacity)
        i_z = round(i_dd * layer_factor, 2)# obciązalność długotrwała
        i_r = round(current * kr_factor, 2) # prąd nastawy zabezpieczenia przeciążeniowego
        i_2 = round(i_r * k2_factor, 2)
        second_condition = bool(1.45 * i_z >= i_2)

        if voltage == 0.23:
            i_b = round(power * 1000 / (power_factor * voltage * 1000), 2) # prąd szczytowy obwodu
            delta_u = round(2 * power * 1000 * length * 100 / (
                    56 * float(cable_cross_section) * pow(voltage * 1000, 2)), 2)
            first_condition = bool(i_z >= i_r >= i_b)
        else:
            i_b = round(power * 1000 / (math.sqrt(3) * power_factor * voltage * 1000), 2)
            delta_u = round(2 * power * 1000 * length * 100 / (
                    56 * float(cable_cross_section) * pow(voltage * 1000, 2)), 2)
            first_condition = bool(i_z >= i_r >= i_b)

        CalculationResult.objects.create(position=position, cir_number=circuit_number, cir_name=receiver_name, cir_voltage=voltage, cir_power=power, cir_cos_fi=power_factor, cir_current=i_b,
                                                  cab_amount=amount, core_amount=core, cab_routing=cable_routing, cab_insulation=insulation, cab_material=material,
                                                  cab_cable_cross_section=float(cable_cross_section), cab_length=length, cab_i_dd=i_dd, cab_kc_factor=layer_factor,
                                                  cab_i_z=i_z, dev_type=device_type, dev_current=current, dev_kr_factor=kr_factor, dev_i_r=i_r,
                                                  dev_k2_factor=k2_factor, dev_i_2=i_2, conditions=str(first_condition), cab_vol_drop=delta_u)

        return render(request, 'main_page.html', context={'voltages': voltages, 'materials': materials,
                                                      'insulations': insulations,
                                                      'cable_cross_sections': cable_cross_sections,
                                                      'cables_routing': cables_routing, 'names': names,
                                                      'currents': currents,
                                                      'times_off': times_off, 'k2_factors': k2_factors,
                                                      'i_r': i_r, 'i_z': i_z, 'i_2': i_2, 'i_b': i_b,
                                                      'delta_u': delta_u, 'first_condition': first_condition,
                                                      'second_condition': second_condition})


class CableListView(LoginRequiredMixin, View):
    def get(self, request):
        results = CalculationResult.objects.all().order_by('position')
        return render(request, 'cable_list.html', context={'results': results})


class PositionChange(LoginRequiredMixin, View):
    def post(self, request):
        pos_nr = request.POST.get('pos_nr')
        if pos_nr:
            result = CalculationResult.objects.get(position=int(pos_nr))
            if CalculationResult.objects.filter(position=(int(pos_nr) + 1)).exists():
                next_result = CalculationResult.objects.get(position=(int(pos_nr) + 1))
                result.position = int(result.position)
                next_result.position = int(next_result.position)
                result.position += 1
                result.save()
                next_result.position -= 1
                next_result.save()
                return JsonResponse({'status': 'ok'})
        return JsonResponse({'status': 'bad'})

class CableIddView(LoginRequiredMixin, View):
    def get(self, request):
        cables = Cable.objects.all()
        cable_select_form = CableSelectForm()
        return render(request, 'display_idd.html', context={'cables': cables, 'cable_select_form': cable_select_form})
    def post(self, request):
        cables = Cable.objects.all()
        cable_select_form = CableSelectForm(request.POST)
        if cable_select_form.is_valid():
            material = cable_select_form.cleaned_data.get('material')
            insulation = cable_select_form.cleaned_data.get('insulation')
            cable_cross_section = cable_select_form.cleaned_data.get('cable_cross_section')
            cable_routing = cable_select_form.cleaned_data.get('cable_routing')

            result = Cable.objects.filter(material=material, insulation=insulation,
                                          cable_cross_section=cable_cross_section, cable_routing=cable_routing)[0]
            return render(request, 'display_idd.html', context={'cables': cables, 'cable_select_form': cable_select_form, 'result': result})


#TODO: wyświetlanie danych
class DisplayCableView(LoginRequiredMixin, View):
    def get(self, request):
        cables = Cable.objects.all()
        return render(request, 'display_cable.html', context={'cables': cables})


class DisplayDevicesView(View):
    def get(self, request):
        devices = ProtectionDevices.objects.all()
        return render(request, 'display_device.html', context={'devices': devices})


#TODO: edit data
class EditCableView(LoginRequiredMixin, View):
    def get(self, request, cable_id):
        cable = Cable.objects.get(pk=cable_id)
        cable_form = CableForm(instance=cable)
        return render(request, "edit_cable.html", context={"form": cable_form})
    def post(self, request, cable_id):
        cable = Cable.objects.get(pk=cable_id)
        cable_form = CableForm(request.POST, instance=cable)
        if cable_form.is_valid():
            cable_form.save()
            return redirect('elecCalc:display-cable')


class EditDeviceView(LoginRequiredMixin, View):

elecCalc/templates/add_cable.html
{% extends "base.html" %}
{% block content %}
<h4 class="account-heading">Dodaj kabla:</h4>
<form action="#" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock content %}

elecCalc/templates/add_device.html
{% extends "base.html" %}
{% block content %}
<h4 class="account-heading">Dodaj zabezpieczenie:</h4>
<form action="#" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock content %}

elecCalc/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <meta charset="utf-8">
    <title>Dobór kabli i zabezpieczeń:</title>
</head>
<body>
    <header>
		<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
			<a class="navbar-brand" href="#"><img src="" width="30" height="30" class="d-inline-block mr-1 align-bottom" alt=""> logo</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainmenu" aria-controls="mainmenu" aria-expanded="false" aria-label="Przełącznik nawigacji">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="mainmenu">
				<ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-expanded="false" id="submenu" aria-haspopup="true"> <img class="save" src="{% static "save.png" %}" width="20" height="20" alt="Zapisz"></a>
						<ul class="dropdown-menu" aria-labelledby="submenu">
							<a class="dropdown-item" href="{% url 'elecCalc:csv' %}"> Zapisz do CSV </a>
							<a class="dropdown-item" href="{% url 'elecCalc:display-device' %}"> Zapisz do PDF </a>
						</ul>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-expanded="false" id="submenu" aria-haspopup="true"> Admin </a>
						<ul class="dropdown-menu" aria-labelledby="submenu">
							<a class="dropdown-item" href="{% url 'elecCalc:display-cable' %}"> Baza kabli </a>
							<a class="dropdown-item" href="{% url 'elecCalc:display-device' %}"> Baza zabezpieczeń </a>
						</ul>
					</li>

					<li class="nav-item">
						<a class="nav-link" href="{% url 'elecCalc:main_page' %}"> Dobór kabli </a>
					</li>

					<li class="nav-item">
						<a class="nav-link" href="{% url 'elecCalc:cable-list' %}"> Lista kablowa </a>
					</li>

					<li class="nav-item">
						<a class="nav-link disabled" href="#"> Bilans mocy </a>
					</li>

                    <li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-expanded="false" id="submenu" aria-haspopup="true"> Dodatki </a>
						<ul class="dropdown-menu" aria-labelledby="submenu">
							<a class="dropdown-item" href="{% url 'elecCalc:display-idd' %}"> Tabela obciążalności kabli </a>
						</ul>
					</li>

				</ul>

				<form class="form-inline">
					<input class="form-control mr-1" type="search" placeholder="Wyszukaj" aria-label="Wyszukaj">
					<button class="btn btn-light" type="submit">Znajdź</button>
				</form>
                <ul class="navbar-nav mr-auto">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item m-2">
                            Witaj, {{ request.user.username }}!
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'elecCalc:logout' %}"> Wyloguj </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'elecCalc:login' %}"> Zaloguj </a>
                        </li>

                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'elecCalc:register' %}"> Rejestracja </a>
                        </li>
                    {% endif %}
                </ul>
			</div>
		</nav>
	</header>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

elecCalc/templates/display_cable.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<h4 class="account-heading">Zestawienie kabli:</h4>
    <div class="col-1"><a href="{% url 'elecCalc:add-cable'%}"><img src="{% static "text-plus-icon.png" %}" alt="Trash"></a></div>
    <div class="row">
        <div class="col-1">Materiał</div>
        <div class="col-1">Izolacja</div>
        <div class="col-1">Przekrój [mm2]</div>
        <div class="col-1">Ułożenie</div>
        <div class="col-1">Obciążalność [A]</div>
    </div>
    {% for cable in cables %}
    <div class="row">
        <div class="col-1">{{ cable.get_material_display }}</div>
        <div class="col-1">{{ cable.get_insulation_display }}</div>
        <div class="col-1">{{ cable.get_cable_cross_section_display }}</div>
        <div class="col-1">{{ cable.get_cable_routing_display }}</div>
        <div class="col-1">{{ cable.capacity }}</div>
        <div class="col-1"><a href="{% url 'elecCalc:delete-cable' cable.id %}"><img src="{% static "trash.png" %}" alt="Trash" width="30%" height="70%"></a></div>
        <div class="col-1"><a href="{% url 'elecCalc:edit-cable' cable.id %}"><img src="{% static "edit.png" %}" alt="Edit" width="30%" height="70%"></a></div>
    </div>
    {% endfor %}
{% endblock content %}

elecCalc/templates/display_device.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<h4 class="account-heading">Zestawienie zabezpieczeń:</h4>
    <div class="col-1"><a href="{% url 'elecCalc:add-device' %}"><img src="{% static "text-plus-icon.png" %}" alt="Trash"></a></div>
    <div class="row">
        <div class="col-3">Nazwa</div>
        <div class="col-1">Typ</div>
        <div class="col-1">Prąd [A]</div>
    </div>
    {% for device in devices %}
    <div class="row">
        <div class="col-3">{{ device.get_name_display }}</div>
        <div class="col-1">{{ device.get_type_display }}</div>
        <div class="col-1">{{ device.get_current_display }}</div>
        <div class="col-1"><a href="{% url 'elecCalc:delete-device' device.id %}"><img src="{% static "trash.png" %}" alt="Trash" width="30%" height="70%"></a></div>
        <div class="col-1"><a href="{% url 'elecCalc:edit-device' device.id %}"><img src="{% static "edit.png" %}" alt="Edit" width="30%" height="70%"></a></div>
    </div>
    {% endfor %}
{% endblock content %}

elecCalc/templates/display_idd.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<h6 class="account-heading mt-3">Filtruj:</h6>
<form action="#" method="post">
    {% csrf_token %}
    <div class="form-row ">
        <div class="form-group col-md-12 mb-0">
            {% crispy cable_select_form %}
        </div>
        <div class="form-group col-md-12 mb-0" id="idd">
            Iz = {{ result.capacity }} A
        </div>
        <div class="form-group col-md-12 mb-0 mt-3">
            <input type="submit" class="btn btn-primary" value="Szukaj">
        </div>
    </div>
</form>
<h6 class="account-heading mt-3">Lista obciążalności długotrwałej:</h6>
<div class="row mt-3">
    <div class="col-1">Materiał
        <a href=""><img src="{% static "sort.png" %}" alt="Sortuj"></a>
    </div>
    <div class="col-1">Izolacja
        <a href=""><img src="{% static "sort.png" %}" alt="Sortuj"></a>
    </div>
    <div class="col-1">Przekrój [mm2]
        <a href=""><img src="{% static "sort.png" %}" alt="Sortuj"></a>
    </div>
    <div class="col-1">Ułożenie
        <a href=""><img src="{% static "sort.png" %}" alt="Sortuj"></a>
    </div>
    <div class="col-1">Obciążalność [A]</div>
</div>
{% for cable in cables %}
<div class="row">
    <div class="col-1">{{ cable.get_material_display }}</div>
    <div class="col-1">{{ cable.get_insulation_display }}</div>
    <div class="col-1">{{ cable.get_cable_cross_section_display }}</div>
    <div class="col-1">{{ cable.get_cable_routing_display }}</div>
    <div class="col-1">{{ cable.capacity }}</div>
</div>
{% endfor %}
{% endblock content %}

elecCalc/templates/edit_cable.html
{% extends "base.html" %}
{% block content %}
<h4 class="account-heading">Edycja kabla:</h4>
<form action="#" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock content %}

elecCalc/templates/edit_device.html
{% extends "base.html" %}
{% block content %}
<h4 class="account-heading">Edycja zabezpieczeń:</h4>
<form action="#" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock content %}